on:
  push:
    branches:
      - master
      
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python3 my_test.py
  formating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install black
      - run: python3 -m black app.py
      - run: python3 -m black config.py
      - run: python3 -m black check_encode.py
      - run: python3 -m black create_table.py
      - run: python3 -m black display_list.py
      - run: python3 -m black run.py
      - run: python3 -m black shorty_api.py
      - run: python3 -m black sql_table.py
  code-review:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install flake8
      - run: python3 -m flake8 --ignore E203,F401,W291,F821,E302,W191,E501,E251,E231,E502,E101,E128,E712,E222,E303,W293,F841,E226,E202,E127,E241,E305 app.py
      - run: python3 -m flake8 config.py
      - run: python3 -m flake8 check_encode.py
      - run: python3 -m flake8 create_table.py
      - run: python3 -m flake8 display_list.py
      - run: python3 -m flake8 run.py
      - run: python3 -m flake8 shorty_api.py
      - run: python3 -m flake8 sql_table.py
