on:
  push:
    branches:
      - master
      
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python3 my_test.py
  formating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install black
      - run: python3 -m black app.py
      - run: python3 -m black config.py
      - run: python3 -m black check_encode.py
      - run: python3 -m black create_table.py
      - run: python3 -m black display_list.py
      - run: python3 -m black run.py
      - run: python3 -m black shorty_api.py
      - run: python3 -m black sql_table.py
  code-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install pyflakes
      - run: python3 -m pyflakes app.py
      - run: python3 -m pyflakes config.py
      - run: python3 -m pyflakes check_encode.py
      - run: python3 -m pyflakes create_table.py
      - run: python3 -m pyflakes display_list.py
      - run: python3 -m pyflakes run.py
      - run: python3 -m pyflakes shorty_api.py
      - run: python3 -m pyflakes sql_table.py
